In [1]:
import pandas as pd

In [2]:
a = {
    'Name': ['Gojo', 'Sukuna', 'Yuji', 'Mahoraga','Yuta', 'Megumi', 'Toji', 'Maki'],
    'Age': [23,100,19,453,32,25,34,25],
    'Score': [80,60,97,47,63,84,73,68]
}

In [3]:
data = pd.DataFrame(a)
data

       Name  Age  Score
0      Gojo   23     80
1    Sukuna  100     60
2      Yuji   19     97
3  Mahoraga  453     47
4      Yuta   32     63
5    Megumi   25     84
6      Toji   34     73
7      Maki   25     68

In [4]:
# Top -5 rows from upside
data.head(4)

       Name  Age  Score
0      Gojo   23     80
1    Sukuna  100     60
2      Yuji   19     97
3  Mahoraga  453     47

In [5]:
data.head() # if we not give value bydefault it will print 5 rows

       Name  Age  Score
0      Gojo   23     80
1    Sukuna  100     60
2      Yuji   19     97
3  Mahoraga  453     47
4      Yuta   32     63

In [6]:
# top -5 rows from downside
data.tail(3)

     Name  Age  Score
5  Megumi   25     84
6    Toji   34     73
7    Maki   25     68

In [7]:
data.tail() # if we not give value bydefault it will print 5 rows

       Name  Age  Score
3  Mahoraga  453     47
4      Yuta   32     63
5    Megumi   25     84
6      Toji   34     73
7      Maki   25     68

In [8]:
data.shape

(8, 3)

In [9]:
data.info() # to find the types of data .  which types are there (string(object), integer, float)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      int64
 2   Score   8 non-null      int64
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes

In [10]:
data.dtypes # finding datatypes in column

Name     object
Age       int64
Score     int64
dtype: object

SELECTING COLUMNS AND ROWS

In [11]:
data['Age'] # for getting particular columns

0     23
1    100
2     19
3    453
4     32
5     25
6     34
7     25
Name: Age, dtype: int64

In [12]:
data[['Name','Age']] # for multiple columns

       Name  Age
0      Gojo   23
1    Sukuna  100
2      Yuji   19
3  Mahoraga  453
4      Yuta   32
5    Megumi   25
6      Toji   34
7      Maki   25

In [13]:
# .loc (df.loc[row_label,col_label])      FOR FINDING DIRECT LOCATION
data.loc[4,'Name'] # getting any particular value after giving index and column name

'Yuta'

In [14]:
data.loc[1:5,['Name','Score']]

       Name  Score
1    Sukuna     60
2      Yuji     97
3  Mahoraga     47
4      Yuta     63
5    Megumi     84

In [15]:
# index location 
#.iloc (row_index,col_index)
data.iloc[3] #getting full detail of spcific location

Name     Mahoraga
Age           453
Score          47
Name: 3, dtype: object

In [16]:
data.iloc[0:3,0:2]

     Name  Age
0    Gojo   23
1  Sukuna  100
2    Yuji   19

INDEX 
RamgeIndex (start=0, stop=9, steps= 1)

In [17]:
data.values # getting the value in form of list

array([['Gojo', 23, 80],
       ['Sukuna', 100, 60],
       ['Yuji', 19, 97],
       ['Mahoraga', 453, 47],
       ['Yuta', 32, 63],
       ['Megumi', 25, 84],
       ['Toji', 34, 73],
       ['Maki', 25, 68]], dtype=object)

In [18]:
data.columns # getting the name of columns

Index(['Name', 'Age', 'Score'], dtype='object')

In [19]:
data.values.shape

(8, 3)

RENAME COLUMNS

In [20]:
c = data.rename(columns={'Score':'Marks'}) # #changing the column name or give new name 
c

       Name  Age  Marks
0      Gojo   23     80
1    Sukuna  100     60
2      Yuji   19     97
3  Mahoraga  453     47
4      Yuta   32     63
5    Megumi   25     84
6      Toji   34     73
7      Maki   25     68

In [21]:
c = data.rename(columns={'Score':'Marks','Age':'age'})
c

       Name  age  Marks
0      Gojo   23     80
1    Sukuna  100     60
2      Yuji   19     97
3  Mahoraga  453     47
4      Yuta   32     63
5    Megumi   25     84
6      Toji   34     73
7      Maki   25     68

SET INDEX

In [22]:
d = data.set_index('Name') ## we can change the index according to you
d

          Age  Score
Name
Gojo       23     80
Sukuna    100     60
Yuji       19     97
Mahoraga  453     47
Yuta       32     63
Megumi     25     84
Toji       34     73
Maki       25     68

RESET INDEX

In [23]:
e = d.reset_index()
e

       Name  Age  Score
0      Gojo   23     80
1    Sukuna  100     60
2      Yuji   19     97
3  Mahoraga  453     47
4      Yuta   32     63
5    Megumi   25     84
6      Toji   34     73
7      Maki   25     68