# 🐼 Pandas - Class 8: Working with Time Series
Welcome to **Class 8** of our Pandas series. Today we’ll learn how to handle and analyze time series data.

## 1. Converting Columns to Datetime (`pd.to_datetime`)
- Use `pd.to_datetime()` to convert strings or numbers into datetime objects.
- Once converted, Pandas recognizes them as dates, enabling powerful operations.

In [1]:
import pandas as pd

# 1. Create the dataset
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "OrderDate": ["2024-01-05", "2024/01/12", "15-01-2024", "2024-01-20", "20240125"],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Amount": [250, 400, 150, 300, 500]
}

df = pd.DataFrame(data)

In [2]:
df

   OrderID   OrderDate Customer  Amount
0     1001  2024-01-05    Alice     250
1     1002  2024/01/12      Bob     400
2     1003  15-01-2024  Charlie     150
3     1004  2024-01-20    David     300
4     1005    20240125     Emma     500

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    5 non-null      int64
 1   OrderDate  5 non-null      object
 2   Customer   5 non-null      object
 3   Amount     5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [4]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'],errors="coerce",format="mixed")

In [5]:
df

   OrderID  OrderDate Customer  Amount
0     1001 2024-01-05    Alice     250
1     1002 2024-01-12      Bob     400
2     1003 2024-01-15  Charlie     150
3     1004 2024-01-20    David     300
4     1005 2024-01-25     Emma     500

## 2. Setting DateTime Index & Resampling
- Set a datetime column as the index with `set_index()`.
- Resample time series using `resample('M').mean()` or other rules ('D', 'W', 'Y').
- Useful for aggregating data by time periods.

In [6]:
  # 1- Convert OrderDate to datetime 
df["OrderDate"] = pd.to_datetime(df["OrderDate"],errors="coerce",format="mixed")

# 2- Set OrderDate as index 
df_indx = df.set_index("OrderDate")
print(df_indx)

# 3- resample by month to compute total amount 
# Fixed: Changed from resample("ME")("Amount") to resample("ME")["Amount"]
monthly_total = df_indx.resample("ME")["Amount"].sum()
print(monthly_total) 

# 4- Resample by week to compute averge amount
weekly_total = df_indx.resample("W")["Amount"].sum()
print(weekly_total)

w_avg = df_indx.resample("W")["Amount"].mean()
print(w_avg)

            OrderID Customer  Amount
OrderDate
2024-01-05     1001    Alice     250
2024-01-12     1002      Bob     400
2024-01-15     1003  Charlie     150
2024-01-20     1004    David     300
2024-01-25     1005     Emma     500
OrderDate
2024-01-31    1600
Freq: ME, Name: Amount, dtype: int64
OrderDate
2024-01-07    250
2024-01-14    400
2024-01-21    450
2024-01-28    500
Freq: W-SUN, Name: Amount, dtype: int64
OrderDate
2024-01-07    250.0
2024-01-14    400.0
2024-01-21    225.0
2024-01-28    500.0
Freq: W-SUN, Name: Amount, dtype: float64

## mini-project 

Converting columns to datetime (pd.to_datetime)

Setting a DateTime index & resampling

In [7]:
import pandas as pd

# 1️⃣ Create a dataset of website visits (string dates + visit counts)
data = {
    "VisitDate": [
        "2024-01-03", "2024/01/08", "15-01-2024",
        "2024-02-02", "2024-02-15",
        "2024/03/01", "2024-03-12", "01-04-2024"
    ],
    "Visitors": [120, 150, 90, 200, 180, 220, 210, 300]
}

df = pd.DataFrame(data)

# 2️⃣ Convert VisitDate to datetime
# Write your code here
df["VisitDate"] = pd.to_datetime(df["VisitDate"],errors = "coerce",format="mixed")
print(df)

# 3️⃣ Set VisitDate as the index
# Write your code here
visiter_index=df.set_index("VisitDate")
print(visiter_index)
# 4️⃣ Resample to get total visitors per month
# Write your code here

print(visiter_index.resample("M")["Visitors"].sum())

# 5️⃣ Resample to get average visitors per week
# Write your code here
print(visiter_index.resample("W")["Visitors"].mean())

   VisitDate  Visitors
0 2024-01-03       120
1 2024-01-08       150
2 2024-01-15        90
3 2024-02-02       200
4 2024-02-15       180
5 2024-03-01       220
6 2024-03-12       210
7 2024-01-04       300
            Visitors
VisitDate
2024-01-03       120
2024-01-08       150
2024-01-15        90
2024-02-02       200
2024-02-15       180
2024-03-01       220
2024-03-12       210
2024-01-04       300
VisitDate
2024-01-31    660
2024-02-29    380
2024-03-31    430
Freq: ME, Name: Visitors, dtype: int64
VisitDate
2024-01-07    210.0
2024-01-14    150.0
2024-01-21     90.0
2024-01-28      NaN
2024-02-04    200.0
2024-02-11      NaN
2024-02-18    180.0
2024-02-25      NaN
2024-03-03    220.0
2024-03-10      NaN
2024-03-17    210.0
Freq: W-SUN, Name: Visitors, dtype: float64

C:\Users\TUF\AppData\Local\Temp\ipykernel_7080\3673818459.py:27: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  print(visiter_index.resample("M")["Visitors"].sum())

---
## Summary
- Converted columns to datetime with `pd.to_datetime`.
- Set DateTime index and resampled data.
- Performed date-based filtering and slicing.
- Applied rolling and expanding window calculations.